name: erllambda_dummy_build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:22.0.7

    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: make compile
    - name: Run tests
      run: make test
    - name: Fail trigger
      run: exit13 # full stop

