name: erllambda_dummy_build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  GITHUB_WORKFLOW_URL: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:22.0.7

    steps:
    - uses: actions/checkout@v2
   
    - name: Compile
      run: make compile
   
    - name: Run tests
      run: make test
   
      #    - name: Fail trigger
      #run: exit13 # full stop
   
    - name: Microsoft Teams Notification
      uses: dhollerbach/github-action-send-message-to-ms-teams@1.0.10
      if: always()
      with:
        webhook: ${{ secrets.TEAMS_WEBHOOK }}
        message: ' Job ${{ github.workflow }} | ${{ github.run_number }}: ${{ job.status }} Notification: ${{github.event.pusher.name}} have pushed something. ${{env.GITHUB_WORKFLOW_URL}}'

