name: erllambda_dummy_build_nightly

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  nightly_build:

    runs-on: ubuntu-latest

    container:
      image: erlang:22.0.7

    steps:
    - uses: actions/checkout@v2
    - name: say hello
      run: echo 'Hello world!'
