name: erllambda_ownworker

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:

  build_release:

    runs-on: self-hosted

    container:
      image: erlang:22.0.7

    steps:
    - name: Checkout alcfn
      run: |
        git clone git@algithub.pd.alertlogic.net:alertlogic/cd15-pipeline-toolchain.git ;
        cd cd15-pipeline-toolchain ;
        ls -lt ;
    
    - uses: actions/checkout@v2
    - name: Compile
      run: make compile
      
    - name: Run tests
      run: make test
